### ISSUE TITLE
Does it still works? 

### ISSUE THREAD

**Issue by X-Tender** [leyyinad/alfred2-mite-workflow#1]
I've installed the workflow previously and all I was able to do is to stop the tracker. How can I start a specific task in  specific project? :)

**Comment by leyyinad** [comment]
This used to work back then. You just typed `mt ` and it listed your projects. But since my Company switched to TeamGrid I haven't used this in a while and won't maintain it any longer. Sorry. Maybe it has to do something with Alfred 3?

**Comment by X-Tender** [comment]
Ok thanks. I try to figure it out and make then a pul request.

**Comment by X-Tender** [comment]
Ok I've figured it out.
The workflow.php needs to be udpatet to alfred3 on line 41 nad 42, and in the mite.php the timezone have to besetted at the top of the file via `date_default_timezone_set('Europe/Berlin');`for example.

**Comment by leyyinad** [comment]
Great, can you do a PR? I'll merge it instantly.

**Comment by X-Tender** [comment]
I will do later. would also like to make some improvements. Currently I get all recently started tasks (also from other users) I dont know if this is intended. :)

**Comment by leyyinad** [comment]
Great! Sorry, I can't remember, it's much too long ago. But looking at the last commit, this is from a time when I used this as a freelancer, as a single user. Looks like I event haven't brought this thing to my company back then. This is something I'd fix nowadays. But as I said, we moved away from Mite because our requirements changed.

**Comment by X-Tender** [comment]
Ok, I will make a pull request later with the fix first and then with the improvements.
